---
name: Github action
on:
  - push
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.0.0'
      - name: building the project
        run: npm run dev
      - name: Setup finish
        run: echo "Operation Completed"
